#===============================================================================
# pin_pad_physical_constraints.tcl
#
# This script is responsible for constraining the IO driver cells. After this
# script is sourced, the palce_io command will be called which will then use
# these constraints to physically place all of the IO cells.
#===============================================================================

puts "BSG-info: Running script [info script]\n"

# Offset needs to give us space for the crackstop (14) distance to guard edge
# in the crackstop (7) and then room for the pad overhang (13.707) which totals
# to 34.707 (rounded up to 35 for now). It is possible to remove that 13.707
# overhand by RDL routing to PADs that are further in the die area. This will
# increase bond angles so we should be careful that packaging is still feasible
# if we do this.
create_io_ring -name io_ring -offset 35.000

#===============================================================================
# LEFT IO CELLS (IN ORDER!)
#===============================================================================

set left_io_cells [list]
lappend left_io_cells "ddr_dq_8_io"
lappend left_io_cells "vdd_l_0"
lappend left_io_cells "ddr_dq_9_io"
lappend left_io_cells "vss_l_0"
lappend left_io_cells "ddr_dq_10_io"
lappend left_io_cells "v18_l_0"
lappend left_io_cells "ddr_dq_11_io"
lappend left_io_cells "vzz_l_0"
lappend left_io_cells "ddr_dq_12_io"
lappend left_io_cells "vdd_l_1"
lappend left_io_cells "ddr_dq_13_io"
lappend left_io_cells "vss_l_1"
lappend left_io_cells "bias_l_0"
lappend left_io_cells "ddr_dq_14_io"
lappend left_io_cells "v18_l_1"
lappend left_io_cells "ddr_dq_15_io"
lappend left_io_cells "vzz_l_1"
lappend left_io_cells "ddr_dqs_p_0_io"
lappend left_io_cells "vdd_l_2"
lappend left_io_cells "ddr_dqs_n_0_io"
lappend left_io_cells "vss_l_2"
lappend left_io_cells "ddr_dm_0_o"
lappend left_io_cells "v18_l_2"
lappend left_io_cells "ddr_dq_0_io"
lappend left_io_cells "vzz_l_2"
lappend left_io_cells "ddr_dq_1_io"
lappend left_io_cells "vdd_l_3"
lappend left_io_cells "bias_l_1"
lappend left_io_cells "ddr_dq_2_io"
lappend left_io_cells "vss_l_3"
lappend left_io_cells "ddr_dq_3_io"
lappend left_io_cells "v18_l_3"
lappend left_io_cells "ddr_dq_4_io"
lappend left_io_cells "vzz_l_3"
lappend left_io_cells "ddr_dq_5_io"
lappend left_io_cells "vdd_l_4"
lappend left_io_cells "ddr_dq_6_io"
lappend left_io_cells "vss_l_4"
lappend left_io_cells "ddr_dq_7_io"
lappend left_io_cells "v18_l_4"
lappend left_io_cells "bsg_tag_data_o"
lappend left_io_cells "bias_l_2"
lappend left_io_cells "vzz_l_4"
lappend left_io_cells "bsg_tag_clk_o"
lappend left_io_cells "vdd_l_5"
lappend left_io_cells "co2_0_o"
lappend left_io_cells "vss_l_5"
lappend left_io_cells "co2_1_o"
lappend left_io_cells "v18_l_5"
lappend left_io_cells "co2_2_o"
lappend left_io_cells "vzz_l_5"
lappend left_io_cells "co2_3_o"
lappend left_io_cells "vdd_l_6"
lappend left_io_cells "co2_4_o"
lappend left_io_cells "vss_l_6"
lappend left_io_cells "co2_clk_o"
lappend left_io_cells "bias_l_3"
lappend left_io_cells "v18_l_6"
lappend left_io_cells "co2_tkn_i"
lappend left_io_cells "vzz_l_6"
lappend left_io_cells "co2_v_o"
lappend left_io_cells "vdd_l_7"
lappend left_io_cells "co2_5_o"
lappend left_io_cells "vss_l_7"
lappend left_io_cells "co2_6_o"
lappend left_io_cells "v18_l_7"
lappend left_io_cells "co2_7_o"
lappend left_io_cells "vzz_l_7"
lappend left_io_cells "co2_8_o"

set_signal_io_constraint -io_guide io_ring.left -constraint "{{order_only} [join $left_io_cells]}"

#===============================================================================
# TOP IO CELLS (IN ORDER!)
#===============================================================================

set top_io_cells [list]
lappend top_io_cells "vdd_t_0"
lappend top_io_cells "co_0_i"
lappend top_io_cells "bias_t_0"
lappend top_io_cells "vss_t_0"
lappend top_io_cells "co_1_i"
lappend top_io_cells "v18_t_0"
lappend top_io_cells "co_2_i"
lappend top_io_cells "vzz_t_0"
lappend top_io_cells "co_3_i"
lappend top_io_cells "vdd_t_1"
lappend top_io_cells "co_4_i"
lappend top_io_cells "vss_t_1"
lappend top_io_cells "co_clk_i"
lappend top_io_cells "v18_t_1"
lappend top_io_cells "co_tkn_o"
lappend top_io_cells "vzz_t_1"
lappend top_io_cells "co_v_i"
lappend top_io_cells "vdd_t_2"
lappend top_io_cells "co_5_i"
lappend top_io_cells "vss_t_2"
lappend top_io_cells "bias_t_1"
lappend top_io_cells "co_6_i"
lappend top_io_cells "v18_t_2"
lappend top_io_cells "co_7_i"
lappend top_io_cells "vzz_t_2"
lappend top_io_cells "co_8_i"
lappend top_io_cells "vdd_t_3"
lappend top_io_cells "clk_A_i"
lappend top_io_cells "vss_t_3"
lappend top_io_cells "clk_B_i"
lappend top_io_cells "breaker_t_0"
lappend top_io_cells "v18_t_3"
lappend top_io_cells "clk_C_i"
lappend top_io_cells "vzz_t_3"
lappend top_io_cells "clk_o"
lappend top_io_cells "vdd_pll"
lappend top_io_cells "clk_async_reset_i"
lappend top_io_cells "vss_pll"
lappend top_io_cells "bias_t_2"
lappend top_io_cells "misc_o"
lappend top_io_cells "breaker_t_1"
lappend top_io_cells "vdd_t_4"
lappend top_io_cells "sel_0_i"
lappend top_io_cells "vss_t_4"
lappend top_io_cells "sel_1_i"
lappend top_io_cells "v18_t_4"
lappend top_io_cells "sel_2_i"
lappend top_io_cells "vzz_t_4"
lappend top_io_cells "core_async_reset_i"
lappend top_io_cells "vdd_t_5"
lappend top_io_cells "ci2_0_o"
lappend top_io_cells "vss_t_5"
lappend top_io_cells "ci2_1_o"
lappend top_io_cells "v18_t_5"
lappend top_io_cells "ci2_2_o"
lappend top_io_cells "bias_t_3"
lappend top_io_cells "vzz_t_5"
lappend top_io_cells "ci2_3_o"
lappend top_io_cells "vdd_t_6"
lappend top_io_cells "ci2_4_o"
lappend top_io_cells "vss_t_6"
lappend top_io_cells "ci2_clk_o"
lappend top_io_cells "v18_t_6"
lappend top_io_cells "ci2_tkn_i"
lappend top_io_cells "vzz_t_6"
lappend top_io_cells "ci2_v_o"
lappend top_io_cells "vdd_t_7"
lappend top_io_cells "ci2_5_o"
lappend top_io_cells "vss_t_7"
lappend top_io_cells "ci2_6_o"
lappend top_io_cells "v18_t_7"
lappend top_io_cells "ci2_7_o"
lappend top_io_cells "bias_t_4"
lappend top_io_cells "vzz_t_7"
lappend top_io_cells "ci2_8_o"

set_signal_io_constraint -io_guide io_ring.top -constraint "{{order_only} [join $top_io_cells]}"

#===============================================================================
# RIGHT IO CELLS (IN ORDER!)
#===============================================================================

set right_io_cells [list]
lappend right_io_cells "ci_0_i"
lappend right_io_cells "vdd_r_0"
lappend right_io_cells "ci_1_i"
lappend right_io_cells "vss_r_0"
lappend right_io_cells "ci_2_i"
lappend right_io_cells "v18_r_0"
lappend right_io_cells "ci_3_i"
lappend right_io_cells "vzz_r_0"
lappend right_io_cells "ci_4_i"
lappend right_io_cells "vdd_r_1"
lappend right_io_cells "ci_clk_i"
lappend right_io_cells "bias_r_0"
lappend right_io_cells "vss_r_1"
lappend right_io_cells "ci_tkn_o"
lappend right_io_cells "v18_r_1"
lappend right_io_cells "ci_v_i"
lappend right_io_cells "vzz_r_1"
lappend right_io_cells "ci_5_i"
lappend right_io_cells "vdd_r_2"
lappend right_io_cells "ci_6_i"
lappend right_io_cells "vss_r_2"
lappend right_io_cells "ci_7_i"
lappend right_io_cells "v18_r_2"
lappend right_io_cells "ci_8_i"
lappend right_io_cells "vzz_r_2"
lappend right_io_cells "bsg_tag_en_i"
lappend right_io_cells "bias_r_1"
lappend right_io_cells "vdd_r_3"
lappend right_io_cells "bsg_tag_data_i"
lappend right_io_cells "vss_r_3"
lappend right_io_cells "bsg_tag_clk_i"
lappend right_io_cells "v18_r_3"
lappend right_io_cells "ddr_dm_3_o"
lappend right_io_cells "vzz_r_3"
lappend right_io_cells "ddr_dqs_p_3_io"
lappend right_io_cells "vdd_r_4"
lappend right_io_cells "ddr_dqs_n_3_io"
lappend right_io_cells "vss_r_4"
lappend right_io_cells "ddr_dq_24_io"
lappend right_io_cells "v18_r_4"
lappend right_io_cells "ddr_dq_25_io"
lappend right_io_cells "vzz_r_4"
lappend right_io_cells "ddr_dq_26_io"
lappend right_io_cells "bias_r_2"
lappend right_io_cells "vdd_r_5"
lappend right_io_cells "ddr_dq_27_io"
lappend right_io_cells "vss_r_5"
lappend right_io_cells "ddr_dq_28_io"
lappend right_io_cells "v18_r_5"
lappend right_io_cells "ddr_dq_29_io"
lappend right_io_cells "vzz_r_5"
lappend right_io_cells "ddr_dq_30_io"
lappend right_io_cells "vdd_r_6"
lappend right_io_cells "ddr_dq_31_io"
lappend right_io_cells "vss_r_6"
lappend right_io_cells "ddr_dq_16_io"
lappend right_io_cells "v18_r_6"
lappend right_io_cells "ddr_dq_17_io"
lappend right_io_cells "bias_r_3"
lappend right_io_cells "vzz_r_6"
lappend right_io_cells "ddr_dq_18_io"
lappend right_io_cells "vdd_r_7"
lappend right_io_cells "ddr_dq_19_io"
lappend right_io_cells "vss_r_7"
lappend right_io_cells "ddr_dq_20_io"
lappend right_io_cells "v18_r_7"
lappend right_io_cells "ddr_dq_21_io"
lappend right_io_cells "vzz_r_7"
lappend right_io_cells "ddr_dq_22_io"
lappend right_io_cells "vdd_r_8"
lappend right_io_cells "ddr_dq_23_io"
lappend right_io_cells "vss_r_8"

set_signal_io_constraint -io_guide io_ring.right -constraint "{{order_only} [join $right_io_cells]}"

#===============================================================================
# BOTTOM IO CELLS (IN ORDER!)
#===============================================================================

set bottom_io_cells [list]
lappend bottom_io_cells "ddr_dm_2_o"
lappend bottom_io_cells "v18_b_0"
lappend bottom_io_cells "bias_b_0"
lappend bottom_io_cells "ddr_dqs_p_2_io"
lappend bottom_io_cells "vzz_b_0"
lappend bottom_io_cells "ddr_dqs_n_2_io"
lappend bottom_io_cells "vdd_b_0"
lappend bottom_io_cells "ddr_ck_p_o"
lappend bottom_io_cells "vss_b_0"
lappend bottom_io_cells "ddr_ck_n_o"
lappend bottom_io_cells "v18_b_1"
lappend bottom_io_cells "ddr_cke_o"
lappend bottom_io_cells "vzz_b_1"
lappend bottom_io_cells "ddr_cs_n_o"
lappend bottom_io_cells "vdd_b_1"
lappend bottom_io_cells "ddr_ras_n_o"
lappend bottom_io_cells "vss_b_1"
lappend bottom_io_cells "ddr_cas_n_o"
lappend bottom_io_cells "v18_b_2"
lappend bottom_io_cells "bias_b_1"
lappend bottom_io_cells "ddr_we_n_o"
lappend bottom_io_cells "vzz_b_2"
lappend bottom_io_cells "ddr_reset_n_o"
lappend bottom_io_cells "vdd_b_2"
lappend bottom_io_cells "ddr_odt_o"
lappend bottom_io_cells "vss_b_2"
lappend bottom_io_cells "ddr_addr_0_o"
lappend bottom_io_cells "v18_b_3"
lappend bottom_io_cells "ddr_addr_1_o"
lappend bottom_io_cells "vzz_b_3"
lappend bottom_io_cells "ddr_addr_2_o"
lappend bottom_io_cells "vdd_b_3"
lappend bottom_io_cells "ddr_addr_3_o"
lappend bottom_io_cells "vss_b_3"
lappend bottom_io_cells "ddr_addr_4_o"
lappend bottom_io_cells "v18_b_4"
lappend bottom_io_cells "bias_b_2"
lappend bottom_io_cells "ddr_addr_5_o"
lappend bottom_io_cells "vzz_b_4"
lappend bottom_io_cells "ddr_addr_6_o"
lappend bottom_io_cells "vdd_b_4"
lappend bottom_io_cells "ddr_addr_7_o"
lappend bottom_io_cells "vss_b_4"
lappend bottom_io_cells "ddr_addr_8_o"
lappend bottom_io_cells "v18_b_5"
lappend bottom_io_cells "ddr_addr_9_o"
lappend bottom_io_cells "vzz_b_5"
lappend bottom_io_cells "ddr_addr_10_o"
lappend bottom_io_cells "vdd_b_5"
lappend bottom_io_cells "ddr_addr_11_o"
lappend bottom_io_cells "vss_b_5"
lappend bottom_io_cells "ddr_addr_12_o"
lappend bottom_io_cells "v18_b_6"
lappend bottom_io_cells "bias_b_3"
lappend bottom_io_cells "ddr_addr_13_o"
lappend bottom_io_cells "vzz_b_6"
lappend bottom_io_cells "ddr_addr_14_o"
lappend bottom_io_cells "vdd_b_6"
lappend bottom_io_cells "ddr_addr_15_o"
lappend bottom_io_cells "vss_b_6"
lappend bottom_io_cells "ddr_ba_0_o"
lappend bottom_io_cells "v18_b_7"
lappend bottom_io_cells "ddr_ba_1_o"
lappend bottom_io_cells "vzz_b_7"
lappend bottom_io_cells "ddr_ba_2_o"
lappend bottom_io_cells "vdd_b_7"
lappend bottom_io_cells "ddr_dqs_p_1_io"
lappend bottom_io_cells "vss_b_7"
lappend bottom_io_cells "ddr_dqs_n_1_io"
lappend bottom_io_cells "v18_b_8"
lappend bottom_io_cells "bias_b_4"
lappend bottom_io_cells "ddr_dm_1_o"
lappend bottom_io_cells "vzz_b_8"

set_signal_io_constraint -io_guide io_ring.bottom -constraint "{{order_only} [join $bottom_io_cells]}"

puts "BSG-info: Completed script [info script]\n"

