set_pad_physical_constraints -side 1 -pad_name corner_ul
set_pad_physical_constraints -side 2 -pad_name corner_ur
set_pad_physical_constraints -side 3 -pad_name corner_lr
set_pad_physical_constraints -side 4 -pad_name corner_ll

set_pad_physical_constraints -side 3 -order 68 -min_left_iospace 92.5 -min_right_iospace 10 -pad_name CI_0_I
set_pad_physical_constraints -side 3 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_0
set_pad_physical_constraints -side 3 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_1_I
set_pad_physical_constraints -side 3 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_0
set_pad_physical_constraints -side 3 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_2_I
set_pad_physical_constraints -side 3 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_0
set_pad_physical_constraints -side 3 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_3_I
set_pad_physical_constraints -side 3 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_0
set_pad_physical_constraints -side 3 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_4_I
set_pad_physical_constraints -side 3 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_1
set_pad_physical_constraints -side 3 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_CLK_I
set_pad_physical_constraints -side 3 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_1
set_pad_physical_constraints -side 3 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_TKN_O
set_pad_physical_constraints -side 3 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_1
set_pad_physical_constraints -side 3 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_V_I
set_pad_physical_constraints -side 3 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_1
set_pad_physical_constraints -side 3 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_5_I
set_pad_physical_constraints -side 3 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_2
set_pad_physical_constraints -side 3 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_6_I
set_pad_physical_constraints -side 3 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_2
set_pad_physical_constraints -side 3 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_7_I
set_pad_physical_constraints -side 3 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_2
set_pad_physical_constraints -side 3 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI_8_I
set_pad_physical_constraints -side 3 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_2
set_pad_physical_constraints -side 3 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name BSG_TAG_EN_I
set_pad_physical_constraints -side 3 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_3
set_pad_physical_constraints -side 3 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name BSG_TAG_DATA_I
set_pad_physical_constraints -side 3 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_3
set_pad_physical_constraints -side 3 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name BSG_TAG_CLK_I
set_pad_physical_constraints -side 3 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_3
set_pad_physical_constraints -side 3 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DM_3_O
set_pad_physical_constraints -side 3 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_3
set_pad_physical_constraints -side 3 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_P_3_IO
set_pad_physical_constraints -side 3 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_4
set_pad_physical_constraints -side 3 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_N_3_IO
set_pad_physical_constraints -side 3 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_4
set_pad_physical_constraints -side 3 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_24_IO
set_pad_physical_constraints -side 3 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_4
set_pad_physical_constraints -side 3 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_25_IO
set_pad_physical_constraints -side 3 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_4
set_pad_physical_constraints -side 3 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_26_IO
set_pad_physical_constraints -side 3 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_5
set_pad_physical_constraints -side 3 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_27_IO
set_pad_physical_constraints -side 3 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_5
set_pad_physical_constraints -side 3 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_28_IO
set_pad_physical_constraints -side 3 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_5
set_pad_physical_constraints -side 3 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_29_IO
set_pad_physical_constraints -side 3 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_5
set_pad_physical_constraints -side 3 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_30_IO
set_pad_physical_constraints -side 3 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_6
set_pad_physical_constraints -side 3 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_31_IO
set_pad_physical_constraints -side 3 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_6
set_pad_physical_constraints -side 3 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_16_IO
set_pad_physical_constraints -side 3 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_6
set_pad_physical_constraints -side 3 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_17_IO
set_pad_physical_constraints -side 3 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_6
set_pad_physical_constraints -side 3 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_18_IO
set_pad_physical_constraints -side 3 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_7
set_pad_physical_constraints -side 3 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_19_IO
set_pad_physical_constraints -side 3 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_R_7
set_pad_physical_constraints -side 3 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_20_IO
set_pad_physical_constraints -side 3 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_R_7
set_pad_physical_constraints -side 3 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_21_IO
set_pad_physical_constraints -side 3 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_R_7
set_pad_physical_constraints -side 3 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_22_IO
set_pad_physical_constraints -side 3 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_R_8
set_pad_physical_constraints -side 3 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_23_IO
set_pad_physical_constraints -side 3 -order 1  -min_left_iospace 10 -min_right_iospace 92.5 -pad_name VSS_R_8



set_pad_physical_constraints -side 4 -order 68 -min_left_iospace 92.5 -min_right_iospace 10 -pad_name DDR_DM_2_O
set_pad_physical_constraints -side 4 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_0
set_pad_physical_constraints -side 4 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_P_2_IO
set_pad_physical_constraints -side 4 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_0
set_pad_physical_constraints -side 4 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_N_2_IO
set_pad_physical_constraints -side 4 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_0
set_pad_physical_constraints -side 4 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_CK_P_O
set_pad_physical_constraints -side 4 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_0
set_pad_physical_constraints -side 4 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_CK_N_O
set_pad_physical_constraints -side 4 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_1
set_pad_physical_constraints -side 4 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_CKE_O
set_pad_physical_constraints -side 4 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_1
set_pad_physical_constraints -side 4 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_CS_N_O
set_pad_physical_constraints -side 4 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_1
set_pad_physical_constraints -side 4 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_RAS_N_O
set_pad_physical_constraints -side 4 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_1
set_pad_physical_constraints -side 4 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_CAS_N_O
set_pad_physical_constraints -side 4 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_2
set_pad_physical_constraints -side 4 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_WE_N_O
set_pad_physical_constraints -side 4 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_2
set_pad_physical_constraints -side 4 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_RESET_N_O
set_pad_physical_constraints -side 4 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_2
set_pad_physical_constraints -side 4 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ODT_O
set_pad_physical_constraints -side 4 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_2
set_pad_physical_constraints -side 4 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_0_O
set_pad_physical_constraints -side 4 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_3
set_pad_physical_constraints -side 4 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_1_O
set_pad_physical_constraints -side 4 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_3
set_pad_physical_constraints -side 4 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_2_O
set_pad_physical_constraints -side 4 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_3
set_pad_physical_constraints -side 4 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_3_O
set_pad_physical_constraints -side 4 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_3
set_pad_physical_constraints -side 4 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_4_O
set_pad_physical_constraints -side 4 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_4
set_pad_physical_constraints -side 4 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_5_O
set_pad_physical_constraints -side 4 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_4
set_pad_physical_constraints -side 4 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_6_O
set_pad_physical_constraints -side 4 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_4
set_pad_physical_constraints -side 4 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_7_O
set_pad_physical_constraints -side 4 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_4
set_pad_physical_constraints -side 4 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_8_O
set_pad_physical_constraints -side 4 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_5
set_pad_physical_constraints -side 4 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_9_O
set_pad_physical_constraints -side 4 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_5
set_pad_physical_constraints -side 4 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_10_O
set_pad_physical_constraints -side 4 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_5
set_pad_physical_constraints -side 4 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_11_O
set_pad_physical_constraints -side 4 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_5
set_pad_physical_constraints -side 4 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_12_O
set_pad_physical_constraints -side 4 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_6
set_pad_physical_constraints -side 4 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_13_O
set_pad_physical_constraints -side 4 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_6
set_pad_physical_constraints -side 4 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_14_O
set_pad_physical_constraints -side 4 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_6
set_pad_physical_constraints -side 4 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_ADDR_15_O
set_pad_physical_constraints -side 4 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_6
set_pad_physical_constraints -side 4 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_BA_0_O
set_pad_physical_constraints -side 4 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_7
set_pad_physical_constraints -side 4 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_BA_1_O
set_pad_physical_constraints -side 4 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_B_7
set_pad_physical_constraints -side 4 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_BA_2_O
set_pad_physical_constraints -side 4 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_B_7
set_pad_physical_constraints -side 4 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_P_1_IO
set_pad_physical_constraints -side 4 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_B_7
set_pad_physical_constraints -side 4 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_N_1_IO
set_pad_physical_constraints -side 4 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_B_8
set_pad_physical_constraints -side 4 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DM_1_O
set_pad_physical_constraints -side 4 -order 1  -min_left_iospace 10 -min_right_iospace 92.5 -pad_name VZZ_B_8



set_pad_physical_constraints -side 1 -order 1  -min_left_iospace 10 -min_right_iospace 152.5 -pad_name DDR_DQ_8_IO
set_pad_physical_constraints -side 1 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_0
set_pad_physical_constraints -side 1 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_9_IO
set_pad_physical_constraints -side 1 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_0
set_pad_physical_constraints -side 1 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_10_IO
set_pad_physical_constraints -side 1 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_0
set_pad_physical_constraints -side 1 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_11_IO
set_pad_physical_constraints -side 1 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_0
set_pad_physical_constraints -side 1 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_12_IO
set_pad_physical_constraints -side 1 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_1
set_pad_physical_constraints -side 1 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_13_IO
set_pad_physical_constraints -side 1 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_1
set_pad_physical_constraints -side 1 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_14_IO
set_pad_physical_constraints -side 1 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_1
set_pad_physical_constraints -side 1 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_15_IO
set_pad_physical_constraints -side 1 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_1
set_pad_physical_constraints -side 1 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_P_0_IO
set_pad_physical_constraints -side 1 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_2
set_pad_physical_constraints -side 1 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQS_N_0_IO
set_pad_physical_constraints -side 1 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_2
set_pad_physical_constraints -side 1 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DM_0_O
set_pad_physical_constraints -side 1 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_2
set_pad_physical_constraints -side 1 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_0_IO
set_pad_physical_constraints -side 1 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_2
set_pad_physical_constraints -side 1 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_1_IO
set_pad_physical_constraints -side 1 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_3
set_pad_physical_constraints -side 1 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_2_IO
set_pad_physical_constraints -side 1 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_3
set_pad_physical_constraints -side 1 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_3_IO
set_pad_physical_constraints -side 1 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_3
set_pad_physical_constraints -side 1 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_4_IO
set_pad_physical_constraints -side 1 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_3
set_pad_physical_constraints -side 1 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_5_IO
set_pad_physical_constraints -side 1 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_4
set_pad_physical_constraints -side 1 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_6_IO
set_pad_physical_constraints -side 1 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_4
set_pad_physical_constraints -side 1 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name DDR_DQ_7_IO
set_pad_physical_constraints -side 1 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_4
set_pad_physical_constraints -side 1 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name BSG_TAG_DATA_O
set_pad_physical_constraints -side 1 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_4
set_pad_physical_constraints -side 1 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name BSG_TAG_CLK_O
set_pad_physical_constraints -side 1 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_5
set_pad_physical_constraints -side 1 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_0_O
set_pad_physical_constraints -side 1 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_5
set_pad_physical_constraints -side 1 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_1_O
set_pad_physical_constraints -side 1 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_5
set_pad_physical_constraints -side 1 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_2_O
set_pad_physical_constraints -side 1 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_5
set_pad_physical_constraints -side 1 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_3_O
set_pad_physical_constraints -side 1 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_6
set_pad_physical_constraints -side 1 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_4_O
set_pad_physical_constraints -side 1 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_6
set_pad_physical_constraints -side 1 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_CLK_O
set_pad_physical_constraints -side 1 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_6
set_pad_physical_constraints -side 1 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_TKN_I
set_pad_physical_constraints -side 1 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_6
set_pad_physical_constraints -side 1 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_V_O
set_pad_physical_constraints -side 1 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_L_7
set_pad_physical_constraints -side 1 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_5_O
set_pad_physical_constraints -side 1 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_L_7
set_pad_physical_constraints -side 1 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_6_O
set_pad_physical_constraints -side 1 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_L_7
set_pad_physical_constraints -side 1 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO2_7_O
set_pad_physical_constraints -side 1 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_L_7
set_pad_physical_constraints -side 1 -order 65 -min_left_iospace 152.5 -min_right_iospace 10 -pad_name CO2_8_O



set_pad_physical_constraints -side 2 -order 1  -min_left_iospace 10 -min_right_iospace 72.5 -pad_name VDD_T_0
set_pad_physical_constraints -side 2 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_0_O
set_pad_physical_constraints -side 2 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_0
set_pad_physical_constraints -side 2 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_1_O
set_pad_physical_constraints -side 2 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_0
set_pad_physical_constraints -side 2 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_2_O
set_pad_physical_constraints -side 2 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_0
set_pad_physical_constraints -side 2 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_3_O
set_pad_physical_constraints -side 2 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_1
set_pad_physical_constraints -side 2 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_4_O
set_pad_physical_constraints -side 2 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_1
set_pad_physical_constraints -side 2 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_CLK_O
set_pad_physical_constraints -side 2 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_1
set_pad_physical_constraints -side 2 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_TKN_I
set_pad_physical_constraints -side 2 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_1
set_pad_physical_constraints -side 2 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_V_O
set_pad_physical_constraints -side 2 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_2
set_pad_physical_constraints -side 2 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_5_O
set_pad_physical_constraints -side 2 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_2
set_pad_physical_constraints -side 2 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_6_O
set_pad_physical_constraints -side 2 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_2
set_pad_physical_constraints -side 2 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_7_O
set_pad_physical_constraints -side 2 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_2
set_pad_physical_constraints -side 2 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name CO_8_O
set_pad_physical_constraints -side 2 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_3
set_pad_physical_constraints -side 2 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name CLK_A_I
set_pad_physical_constraints -side 2 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_3
set_pad_physical_constraints -side 2 -order 28 -min_left_iospace  0 -min_right_iospace 10 -pad_name CLK_B_I
set_pad_physical_constraints -side 2 -order 29 -min_left_iospace  0 -min_right_iospace  0 -pad_name BREAKER_T_0
set_pad_physical_constraints -side 2 -order 30 -min_left_iospace 10 -min_right_iospace  0 -pad_name V18_T_3
set_pad_physical_constraints -side 2 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name CLK_C_I
set_pad_physical_constraints -side 2 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_3
set_pad_physical_constraints -side 2 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name CLK_O
set_pad_physical_constraints -side 2 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_PLL
set_pad_physical_constraints -side 2 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name CLK_ASYNC_RESET_I
set_pad_physical_constraints -side 2 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_PLL
set_pad_physical_constraints -side 2 -order 37 -min_left_iospace  0 -min_right_iospace 10 -pad_name MISC_O
set_pad_physical_constraints -side 2 -order 38 -min_left_iospace  0 -min_right_iospace  0 -pad_name BREAKER_T_1
set_pad_physical_constraints -side 2 -order 39 -min_left_iospace 10 -min_right_iospace  0 -pad_name VDD_T_4
set_pad_physical_constraints -side 2 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name SEL_0_I
set_pad_physical_constraints -side 2 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_4
set_pad_physical_constraints -side 2 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name SEL_1_I
set_pad_physical_constraints -side 2 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_4
set_pad_physical_constraints -side 2 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name SEL_2_I
set_pad_physical_constraints -side 2 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_4
set_pad_physical_constraints -side 2 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name CORE_ASYNC_RESET_I
set_pad_physical_constraints -side 2 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_5
set_pad_physical_constraints -side 2 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_0_I
set_pad_physical_constraints -side 2 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_5
set_pad_physical_constraints -side 2 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_1_I
set_pad_physical_constraints -side 2 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_5
set_pad_physical_constraints -side 2 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_2_I
set_pad_physical_constraints -side 2 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_5
set_pad_physical_constraints -side 2 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_3_I
set_pad_physical_constraints -side 2 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_6
set_pad_physical_constraints -side 2 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_4_I
set_pad_physical_constraints -side 2 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_6
set_pad_physical_constraints -side 2 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_CLK_I
set_pad_physical_constraints -side 2 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_6
set_pad_physical_constraints -side 2 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_TKN_O
set_pad_physical_constraints -side 2 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_6
set_pad_physical_constraints -side 2 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_V_I
set_pad_physical_constraints -side 2 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name VDD_T_7
set_pad_physical_constraints -side 2 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_5_I
set_pad_physical_constraints -side 2 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name VSS_T_7
set_pad_physical_constraints -side 2 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_6_I
set_pad_physical_constraints -side 2 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name V18_T_7
set_pad_physical_constraints -side 2 -order 68 -min_left_iospace 10 -min_right_iospace 10 -pad_name CI2_7_I
set_pad_physical_constraints -side 2 -order 69 -min_left_iospace 10 -min_right_iospace 10 -pad_name VZZ_T_7
set_pad_physical_constraints -side 2 -order 70 -min_left_iospace 72.5 -min_right_iospace 10 -pad_name CI2_8_I
