set_pad_physical_constraints    -side 1    -pad_name corner_ul
set_pad_physical_constraints    -side 2    -pad_name corner_ur
set_pad_physical_constraints    -side 3    -pad_name corner_lr
set_pad_physical_constraints    -side 4    -pad_name corner_ll

set_pad_physical_constraints    -side 1    -pad_name VDD_B_12             -order 1
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_20_B_3     -order 2
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_10_B_3     -order 3
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_5_B_3      -order 4
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20B_B_3    -order 5
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20A_B_3    -order 6
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_10_B_3     -order 7
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_10             -order 8
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_20_B_2     -order 9
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_10_B_2     -order 10
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_5_B_2      -order 11
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20B_B_2    -order 12
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20A_B_2    -order 13
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_10_B_2     -order 14
set_pad_physical_constraints    -side 1    -pad_name V33_B_10             -order 15
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_11       -order 16
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_10       -order 17
set_pad_physical_constraints    -side 1    -pad_name VSS_B_11             -order 18
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_9        -order 19
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_8        -order 20
set_pad_physical_constraints    -side 1    -pad_name VDD_B_11             -order 21
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_7        -order 22
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_6        -order 23
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_9              -order 24
set_pad_physical_constraints    -side 1    -pad_name sdo_D_tkn_ex_i       -order 25
set_pad_physical_constraints    -side 1    -pad_name V33_B_9              -order 26
set_pad_physical_constraints    -side 1    -pad_name sdo_D_sclk_ex_o      -order 27
set_pad_physical_constraints    -side 1    -pad_name VSS_B_10             -order 28
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_7_o       -order 29
set_pad_physical_constraints    -side 1    -pad_name VDD_B_10             -order 30
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_6_o       -order 31
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_8              -order 32
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_5_o       -order 33
set_pad_physical_constraints    -side 1    -pad_name V33_B_8              -order 34
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_4_o       -order 35
set_pad_physical_constraints    -side 1    -pad_name VSS_B_9              -order 36
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_3_o       -order 37
set_pad_physical_constraints    -side 1    -pad_name VDD_B_9              -order 38
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_2_o       -order 39
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_7              -order 40
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_1_o       -order 41
set_pad_physical_constraints    -side 1    -pad_name V33_B_7              -order 42
set_pad_physical_constraints    -side 1    -pad_name sdo_D_data_0_o       -order 43
set_pad_physical_constraints    -side 1    -pad_name VSS_B_8              -order 44
set_pad_physical_constraints    -side 1    -pad_name sdo_D_ncmd_o         -order 45
set_pad_physical_constraints    -side 1    -pad_name VDD_B_8              -order 46
set_pad_physical_constraints    -side 1    -pad_name sdo_D_token_i        -order 47
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_6              -order 48
set_pad_physical_constraints    -side 1    -pad_name JTAG_TRST_i          -order 49
set_pad_physical_constraints    -side 1    -pad_name V33_B_6              -order 50
set_pad_physical_constraints    -side 1    -pad_name sdo_D_sclk_o         -order 51
set_pad_physical_constraints    -side 1    -pad_name VSS_B_7              -order 52
set_pad_physical_constraints    -side 1    -pad_name JTAG_TCK_i           -order 53
set_pad_physical_constraints    -side 1    -pad_name VDD_B_7              -order 54
set_pad_physical_constraints    -side 1    -pad_name BREAKER_20_B_1       -order 55
set_pad_physical_constraints    -side 1    -pad_name PLL_VZZ_i            -order 56
set_pad_physical_constraints    -side 1    -pad_name VSS_B_6              -order 57
set_pad_physical_constraints    -side 1    -pad_name PLL_V33_i            -order 58
set_pad_physical_constraints    -side 1    -pad_name VDD_B_6              -order 59
set_pad_physical_constraints    -side 1    -pad_name PLL_CLK_i            -order 60
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_5              -order 61
set_pad_physical_constraints    -side 1    -pad_name PLL_VSS_i            -order 62
set_pad_physical_constraints    -side 1    -pad_name V33_B_5              -order 63
set_pad_physical_constraints    -side 1    -pad_name PLL_VDD_i            -order 64
set_pad_physical_constraints    -side 1    -pad_name BREAKER_20_B_0       -order 65
set_pad_physical_constraints    -side 1    -pad_name VSS_B_5              -order 66
set_pad_physical_constraints    -side 1    -pad_name JTAG_TDI_i           -order 67
set_pad_physical_constraints    -side 1    -pad_name VDD_B_5              -order 68
set_pad_physical_constraints    -side 1    -pad_name sdo_C_sclk_o         -order 69
set_pad_physical_constraints    -side 1    -pad_name VSS_B_4              -order 70
set_pad_physical_constraints    -side 1    -pad_name JTAG_TMS_i           -order 71
set_pad_physical_constraints    -side 1    -pad_name VDD_B_4              -order 72
set_pad_physical_constraints    -side 1    -pad_name sdo_C_token_i        -order 73
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_4              -order 74
set_pad_physical_constraints    -side 1    -pad_name sdo_C_ncmd_o         -order 75
set_pad_physical_constraints    -side 1    -pad_name V33_B_4              -order 76
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_0_o       -order 77
set_pad_physical_constraints    -side 1    -pad_name VSS_B_3              -order 78
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_1_o       -order 79
set_pad_physical_constraints    -side 1    -pad_name VDD_B_3              -order 80
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_2_o       -order 81
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_3              -order 82
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_3_o       -order 83
set_pad_physical_constraints    -side 1    -pad_name V33_B_3              -order 84
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_4_o       -order 85
set_pad_physical_constraints    -side 1    -pad_name VSS_B_2              -order 86
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_5_o       -order 87
set_pad_physical_constraints    -side 1    -pad_name VDD_B_2              -order 88
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_6_o       -order 89
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_2              -order 90
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_7_o       -order 91
set_pad_physical_constraints    -side 1    -pad_name V33_B_2              -order 92
set_pad_physical_constraints    -side 1    -pad_name sdo_C_data_8_o       -order 93
set_pad_physical_constraints    -side 1    -pad_name VSS_B_1              -order 94
set_pad_physical_constraints    -side 1    -pad_name sdo_C_sclk_ex_o      -order 95
set_pad_physical_constraints    -side 1    -pad_name VDD_B_1              -order 96
set_pad_physical_constraints    -side 1    -pad_name sdo_C_tkn_ex_i       -order 97
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_1              -order 98
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_5        -order 99
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_4        -order 100
set_pad_physical_constraints    -side 1    -pad_name V33_B_1              -order 101
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_3        -order 102
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_2        -order 103
set_pad_physical_constraints    -side 1    -pad_name VSS_B_0              -order 104
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_1        -order 105
set_pad_physical_constraints    -side 1    -pad_name FILLER_20_B_0        -order 106
set_pad_physical_constraints    -side 1    -pad_name VDD_B_0              -order 107
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_20_B_1     -order 108
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_10_B_1     -order 109
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_5_B_1      -order 110
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20B_B_1    -order 111
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20A_B_1    -order 112
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_10_B_1     -order 113
set_pad_physical_constraints    -side 1    -pad_name VZZ_B_0              -order 114
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_20_B_0     -order 115
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_10_B_0     -order 116
set_pad_physical_constraints    -side 1    -pad_name FILLER_35_5_B_0      -order 117
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20B_B_0    -order 118
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_20A_B_0    -order 119
set_pad_physical_constraints    -side 1    -pad_name FILLER_50_10_B_0     -order 120
set_pad_physical_constraints    -side 1    -pad_name V33_B_0              -order 121

set_pad_physical_constraints    -side 2    -pad_name VZZ_L_6              -order 1
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_5_L_3      -order 2
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_10_L_3     -order 3
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_20_L_3     -order 4
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_10_L_3     -order 5
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20A_L_3    -order 6
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20B_L_3    -order 7
set_pad_physical_constraints    -side 2    -pad_name V33_L_6              -order 8
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_5_L_2      -order 9
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_10_L_2     -order 10
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_20_L_2     -order 11
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_10_L_2     -order 12
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20A_L_2    -order 13
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20B_L_2    -order 14
set_pad_physical_constraints    -side 2    -pad_name VSS_L_16             -order 15
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_11       -order 16
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_10       -order 17
set_pad_physical_constraints    -side 2    -pad_name VDD_L_15             -order 18
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_9        -order 19
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_8        -order 20
set_pad_physical_constraints    -side 2    -pad_name VSS_L_15             -order 21
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_7        -order 22
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_6        -order 23
set_pad_physical_constraints    -side 2    -pad_name VDD_L_14             -order 24
set_pad_physical_constraints    -side 2    -pad_name sdi_B_sclk_ex_i      -order 25
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_5              -order 26
set_pad_physical_constraints    -side 2    -pad_name sdi_B_tkn_ex_o       -order 27
set_pad_physical_constraints    -side 2    -pad_name V33_L_5              -order 28
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_7_i       -order 29
set_pad_physical_constraints    -side 2    -pad_name VSS_L_14             -order 30
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_6_i       -order 31
set_pad_physical_constraints    -side 2    -pad_name VDD_L_13             -order 32
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_5_i       -order 33
set_pad_physical_constraints    -side 2    -pad_name VSS_L_13             -order 34
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_4_i       -order 35
set_pad_physical_constraints    -side 2    -pad_name VDD_L_12             -order 36
set_pad_physical_constraints    -side 2    -pad_name misc_L_7_i           -order 37
set_pad_physical_constraints    -side 2    -pad_name VSS_L_12             -order 38
set_pad_physical_constraints    -side 2    -pad_name sdi_B_sclk_i         -order 39
set_pad_physical_constraints    -side 2    -pad_name VDD_L_11             -order 40
set_pad_physical_constraints    -side 2    -pad_name misc_L_6_i           -order 41
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_4              -order 42
set_pad_physical_constraints    -side 2    -pad_name sdi_B_token_o        -order 43
set_pad_physical_constraints    -side 2    -pad_name V33_L_4              -order 44
set_pad_physical_constraints    -side 2    -pad_name misc_L_5_i           -order 45
set_pad_physical_constraints    -side 2    -pad_name VSS_L_11             -order 46
set_pad_physical_constraints    -side 2    -pad_name sdi_B_ncmd_i         -order 47
set_pad_physical_constraints    -side 2    -pad_name VDD_L_10             -order 48
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_3_i       -order 49
set_pad_physical_constraints    -side 2    -pad_name VSS_L_10             -order 50
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_2_i       -order 51
set_pad_physical_constraints    -side 2    -pad_name VDD_L_9              -order 52
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_1_i       -order 53
set_pad_physical_constraints    -side 2    -pad_name VSS_L_9              -order 54
set_pad_physical_constraints    -side 2    -pad_name sdi_B_data_0_i       -order 55
set_pad_physical_constraints    -side 2    -pad_name VDD_L_8              -order 56
set_pad_physical_constraints    -side 2    -pad_name misc_L_4_i           -order 57
set_pad_physical_constraints    -side 2    -pad_name VSS_L_8              -order 58
set_pad_physical_constraints    -side 2    -pad_name clk_0_n_i            -order 59
set_pad_physical_constraints    -side 2    -pad_name VDD_L_7              -order 60
set_pad_physical_constraints    -side 2    -pad_name clk_0_p_i            -order 61
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_3              -order 62
set_pad_physical_constraints    -side 2    -pad_name misc_L_3_o           -order 63
set_pad_physical_constraints    -side 2    -pad_name V33_L_3              -order 64
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_0_i       -order 65
set_pad_physical_constraints    -side 2    -pad_name VSS_L_7              -order 66
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_1_i       -order 67
set_pad_physical_constraints    -side 2    -pad_name VDD_L_6              -order 68
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_2_i       -order 69
set_pad_physical_constraints    -side 2    -pad_name VSS_L_6              -order 70
set_pad_physical_constraints    -side 2    -pad_name sdi_A_ncmd_i         -order 71
set_pad_physical_constraints    -side 2    -pad_name VDD_L_5              -order 72
set_pad_physical_constraints    -side 2    -pad_name misc_L_2_i           -order 73
set_pad_physical_constraints    -side 2    -pad_name VSS_L_5              -order 74
set_pad_physical_constraints    -side 2    -pad_name sdi_A_sclk_i         -order 75
set_pad_physical_constraints    -side 2    -pad_name VDD_L_4              -order 76
set_pad_physical_constraints    -side 2    -pad_name misc_L_1_i           -order 77
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_2              -order 78
set_pad_physical_constraints    -side 2    -pad_name sdi_A_token_o        -order 79
set_pad_physical_constraints    -side 2    -pad_name V33_L_2              -order 80
set_pad_physical_constraints    -side 2    -pad_name misc_L_0_i           -order 81
set_pad_physical_constraints    -side 2    -pad_name VSS_L_4              -order 82
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_3_i       -order 83
set_pad_physical_constraints    -side 2    -pad_name VDD_L_3              -order 84
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_4_i       -order 85
set_pad_physical_constraints    -side 2    -pad_name VSS_L_3              -order 86
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_5_i       -order 87
set_pad_physical_constraints    -side 2    -pad_name VDD_L_2              -order 88
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_6_i       -order 89
set_pad_physical_constraints    -side 2    -pad_name VSS_L_2              -order 90
set_pad_physical_constraints    -side 2    -pad_name sdi_A_data_7_i       -order 91
set_pad_physical_constraints    -side 2    -pad_name VDD_L_1              -order 92
set_pad_physical_constraints    -side 2    -pad_name sdi_A_tkn_ex_o       -order 93
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_1              -order 94
set_pad_physical_constraints    -side 2    -pad_name sdi_A_sclk_ex_i      -order 95
set_pad_physical_constraints    -side 2    -pad_name V33_L_1              -order 96
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_5        -order 97
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_4        -order 98
set_pad_physical_constraints    -side 2    -pad_name VSS_L_1              -order 99
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_3        -order 100
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_2        -order 101
set_pad_physical_constraints    -side 2    -pad_name VDD_L_0              -order 102
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_1        -order 103
set_pad_physical_constraints    -side 2    -pad_name FILLER_20_L_0        -order 104
set_pad_physical_constraints    -side 2    -pad_name VZZ_L_0              -order 105
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_5_L_1      -order 106
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_10_L_1     -order 107
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_20_L_1     -order 108
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_10_L_1     -order 109
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20A_L_1    -order 110
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20B_L_1    -order 111
set_pad_physical_constraints    -side 2    -pad_name V33_L_0              -order 112
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_5_L_0      -order 113
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_10_L_0     -order 114
set_pad_physical_constraints    -side 2    -pad_name FILLER_35_20_L_0     -order 115
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_10_L_0     -order 116
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20A_L_0    -order 117
set_pad_physical_constraints    -side 2    -pad_name FILLER_50_20B_L_0    -order 118
set_pad_physical_constraints    -side 2    -pad_name VSS_L_0              -order 119

set_pad_physical_constraints    -side 3    -pad_name VDD_T_12             -order 1
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_20_T_3     -order 2
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_10_T_3     -order 3
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_5_T_3      -order 4
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20B_T_3    -order 5
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20A_T_3    -order 6
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_10_T_3     -order 7
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_10             -order 8
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_20_T_2     -order 9
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_10_T_2     -order 10
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_5_T_2      -order 11
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20B_T_2    -order 12
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20A_T_2    -order 13
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_10_T_2     -order 14
set_pad_physical_constraints    -side 3    -pad_name V33_T_10             -order 15
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_13       -order 16
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_12       -order 17
set_pad_physical_constraints    -side 3    -pad_name VSS_T_11             -order 18
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_11       -order 19
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_10       -order 20
set_pad_physical_constraints    -side 3    -pad_name VDD_T_11             -order 21
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_9        -order 22
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_8        -order 23
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_9              -order 24
set_pad_physical_constraints    -side 3    -pad_name sdo_B_tkn_ex_i       -order 25
set_pad_physical_constraints    -side 3    -pad_name V33_T_9              -order 26
set_pad_physical_constraints    -side 3    -pad_name sdo_B_sclk_ex_o      -order 27
set_pad_physical_constraints    -side 3    -pad_name VSS_T_10             -order 28
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_7_o       -order 29
set_pad_physical_constraints    -side 3    -pad_name VDD_T_10             -order 30
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_6_o       -order 31
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_8              -order 32
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_5_o       -order 33
set_pad_physical_constraints    -side 3    -pad_name V33_T_8              -order 34
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_4_o       -order 35
set_pad_physical_constraints    -side 3    -pad_name VSS_T_9              -order 36
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_3_o       -order 37
set_pad_physical_constraints    -side 3    -pad_name VDD_T_9              -order 38
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_2_o       -order 39
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_7              -order 40
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_1_o       -order 41
set_pad_physical_constraints    -side 3    -pad_name V33_T_7              -order 42
set_pad_physical_constraints    -side 3    -pad_name sdo_B_data_0_o       -order 43
set_pad_physical_constraints    -side 3    -pad_name VSS_T_8              -order 44
set_pad_physical_constraints    -side 3    -pad_name sdo_B_ncmd_o         -order 45
set_pad_physical_constraints    -side 3    -pad_name VDD_T_8              -order 46
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_7        -order 47
set_pad_physical_constraints    -side 3    -pad_name sdo_B_token_i        -order 48
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_6              -order 49
set_pad_physical_constraints    -side 3    -pad_name JTAG_TDO_o           -order 50
set_pad_physical_constraints    -side 3    -pad_name V33_T_6              -order 51
set_pad_physical_constraints    -side 3    -pad_name sdo_B_sclk_o         -order 52
set_pad_physical_constraints    -side 3    -pad_name VSS_T_7              -order 53
set_pad_physical_constraints    -side 3    -pad_name SMA_in_n_i           -order 54
set_pad_physical_constraints    -side 3    -pad_name VDD_T_7              -order 55
set_pad_physical_constraints    -side 3    -pad_name SMA_in_p_i           -order 56
set_pad_physical_constraints    -side 3    -pad_name VSS_T_6              -order 57
set_pad_physical_constraints    -side 3    -pad_name misc_T_2_i           -order 58
set_pad_physical_constraints    -side 3    -pad_name VDD_T_6              -order 59
set_pad_physical_constraints    -side 3    -pad_name reset_i              -order 60
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_5              -order 61
set_pad_physical_constraints    -side 3    -pad_name SMA_out_n_o          -order 62
set_pad_physical_constraints    -side 3    -pad_name V33_T_5              -order 63
set_pad_physical_constraints    -side 3    -pad_name SMA_out_p_o          -order 64
set_pad_physical_constraints    -side 3    -pad_name VSS_T_5              -order 65
set_pad_physical_constraints    -side 3    -pad_name misc_T_1_i           -order 66
set_pad_physical_constraints    -side 3    -pad_name VDD_T_5              -order 67
set_pad_physical_constraints    -side 3    -pad_name sdo_A_sclk_o         -order 68
set_pad_physical_constraints    -side 3    -pad_name VSS_T_4              -order 69
set_pad_physical_constraints    -side 3    -pad_name misc_T_0_i           -order 70
set_pad_physical_constraints    -side 3    -pad_name VDD_T_4              -order 71
set_pad_physical_constraints    -side 3    -pad_name sdo_A_token_i        -order 72
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_6        -order 73
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_4              -order 74
set_pad_physical_constraints    -side 3    -pad_name sdo_A_ncmd_o         -order 75
set_pad_physical_constraints    -side 3    -pad_name V33_T_4              -order 76
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_0_o       -order 77
set_pad_physical_constraints    -side 3    -pad_name VSS_T_3              -order 78
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_1_o       -order 79
set_pad_physical_constraints    -side 3    -pad_name VDD_T_3              -order 80
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_2_o       -order 81
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_3              -order 82
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_3_o       -order 83
set_pad_physical_constraints    -side 3    -pad_name V33_T_3              -order 84
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_4_o       -order 85
set_pad_physical_constraints    -side 3    -pad_name VSS_T_2              -order 86
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_5_o       -order 87
set_pad_physical_constraints    -side 3    -pad_name VDD_T_2              -order 88
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_6_o       -order 89
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_2              -order 90
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_7_o       -order 91
set_pad_physical_constraints    -side 3    -pad_name V33_T_2              -order 92
set_pad_physical_constraints    -side 3    -pad_name sdo_A_data_8_o       -order 93
set_pad_physical_constraints    -side 3    -pad_name VSS_T_1              -order 94
set_pad_physical_constraints    -side 3    -pad_name sdo_A_sclk_ex_o      -order 95
set_pad_physical_constraints    -side 3    -pad_name VDD_T_1              -order 96
set_pad_physical_constraints    -side 3    -pad_name sdo_A_tkn_ex_i       -order 97
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_1              -order 98
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_5        -order 99
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_4        -order 100
set_pad_physical_constraints    -side 3    -pad_name V33_T_1              -order 101
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_3        -order 102
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_2        -order 103
set_pad_physical_constraints    -side 3    -pad_name VSS_T_0              -order 104
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_1        -order 105
set_pad_physical_constraints    -side 3    -pad_name FILLER_20_T_0        -order 106
set_pad_physical_constraints    -side 3    -pad_name VDD_T_0              -order 107
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_20_T_1     -order 108
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_10_T_1     -order 109
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_5_T_1      -order 110
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20B_T_1    -order 111
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20A_T_1    -order 112
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_10_T_1     -order 113
set_pad_physical_constraints    -side 3    -pad_name VZZ_T_0              -order 114
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_20_T_0     -order 115
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_10_T_0     -order 116
set_pad_physical_constraints    -side 3    -pad_name FILLER_35_5_T_0      -order 117
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20B_T_0    -order 118
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_20A_T_0    -order 119
set_pad_physical_constraints    -side 3    -pad_name FILLER_50_10_T_0     -order 120
set_pad_physical_constraints    -side 3    -pad_name V33_T_0              -order 121

set_pad_physical_constraints    -side 4    -pad_name VZZ_R_6              -order 1
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_5_R_3      -order 2
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_10_R_3     -order 3
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_20_R_3     -order 4
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_10_R_3     -order 5
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20A_R_3    -order 6
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20B_R_3    -order 7
set_pad_physical_constraints    -side 4    -pad_name V33_R_6              -order 8
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_5_R_2      -order 9
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_10_R_2     -order 10
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_20_R_2     -order 11
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_10_R_2     -order 12
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20A_R_2    -order 13
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20B_R_2    -order 14
set_pad_physical_constraints    -side 4    -pad_name VSS_R_16             -order 15
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_11       -order 16
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_10       -order 17
set_pad_physical_constraints    -side 4    -pad_name VDD_R_15             -order 18
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_9        -order 19
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_8        -order 20
set_pad_physical_constraints    -side 4    -pad_name VSS_R_15             -order 21
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_7        -order 22
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_6        -order 23
set_pad_physical_constraints    -side 4    -pad_name VDD_R_14             -order 24
set_pad_physical_constraints    -side 4    -pad_name sdi_D_sclk_ex_i      -order 25
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_5              -order 26
set_pad_physical_constraints    -side 4    -pad_name sdi_D_tkn_ex_o       -order 27
set_pad_physical_constraints    -side 4    -pad_name V33_R_5              -order 28
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_7_i       -order 29
set_pad_physical_constraints    -side 4    -pad_name VSS_R_14             -order 30
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_6_i       -order 31
set_pad_physical_constraints    -side 4    -pad_name VDD_R_13             -order 32
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_5_i       -order 33
set_pad_physical_constraints    -side 4    -pad_name VSS_R_13             -order 34
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_4_i       -order 35
set_pad_physical_constraints    -side 4    -pad_name VDD_R_12             -order 36
set_pad_physical_constraints    -side 4    -pad_name misc_R_7_i           -order 37
set_pad_physical_constraints    -side 4    -pad_name VSS_R_12             -order 38
set_pad_physical_constraints    -side 4    -pad_name sdi_D_sclk_i         -order 39
set_pad_physical_constraints    -side 4    -pad_name VDD_R_11             -order 40
set_pad_physical_constraints    -side 4    -pad_name misc_R_6_i           -order 41
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_4              -order 42
set_pad_physical_constraints    -side 4    -pad_name sdi_D_token_o        -order 43
set_pad_physical_constraints    -side 4    -pad_name V33_R_4              -order 44
set_pad_physical_constraints    -side 4    -pad_name misc_R_5_i           -order 45
set_pad_physical_constraints    -side 4    -pad_name VSS_R_11             -order 46
set_pad_physical_constraints    -side 4    -pad_name sdi_D_ncmd_i         -order 47
set_pad_physical_constraints    -side 4    -pad_name VDD_R_10             -order 48
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_3_i       -order 49
set_pad_physical_constraints    -side 4    -pad_name VSS_R_10             -order 50
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_2_i       -order 51
set_pad_physical_constraints    -side 4    -pad_name VDD_R_9              -order 52
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_1_i       -order 53
set_pad_physical_constraints    -side 4    -pad_name VSS_R_9              -order 54
set_pad_physical_constraints    -side 4    -pad_name sdi_D_data_0_i       -order 55
set_pad_physical_constraints    -side 4    -pad_name VDD_R_8              -order 56
set_pad_physical_constraints    -side 4    -pad_name misc_R_4_i           -order 57
set_pad_physical_constraints    -side 4    -pad_name VSS_R_8              -order 58
set_pad_physical_constraints    -side 4    -pad_name clk_1_n_i            -order 59
set_pad_physical_constraints    -side 4    -pad_name VDD_R_7              -order 60
set_pad_physical_constraints    -side 4    -pad_name clk_1_p_i            -order 61
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_3              -order 62
set_pad_physical_constraints    -side 4    -pad_name misc_R_3_o           -order 63
set_pad_physical_constraints    -side 4    -pad_name V33_R_3              -order 64
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_0_i       -order 65
set_pad_physical_constraints    -side 4    -pad_name VSS_R_7              -order 66
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_1_i       -order 67
set_pad_physical_constraints    -side 4    -pad_name VDD_R_6              -order 68
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_2_i       -order 69
set_pad_physical_constraints    -side 4    -pad_name VSS_R_6              -order 70
set_pad_physical_constraints    -side 4    -pad_name sdi_C_ncmd_i         -order 71
set_pad_physical_constraints    -side 4    -pad_name VDD_R_5              -order 72
set_pad_physical_constraints    -side 4    -pad_name misc_R_2_i           -order 73
set_pad_physical_constraints    -side 4    -pad_name VSS_R_5              -order 74
set_pad_physical_constraints    -side 4    -pad_name sdi_C_sclk_i         -order 75
set_pad_physical_constraints    -side 4    -pad_name VDD_R_4              -order 76
set_pad_physical_constraints    -side 4    -pad_name misc_R_1_i           -order 77
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_2              -order 78
set_pad_physical_constraints    -side 4    -pad_name sdi_C_token_o        -order 79
set_pad_physical_constraints    -side 4    -pad_name V33_R_2              -order 80
set_pad_physical_constraints    -side 4    -pad_name misc_R_0_i           -order 81
set_pad_physical_constraints    -side 4    -pad_name VSS_R_4              -order 82
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_3_i       -order 83
set_pad_physical_constraints    -side 4    -pad_name VDD_R_3              -order 84
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_4_i       -order 85
set_pad_physical_constraints    -side 4    -pad_name VSS_R_3              -order 86
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_5_i       -order 87
set_pad_physical_constraints    -side 4    -pad_name VDD_R_2              -order 88
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_6_i       -order 89
set_pad_physical_constraints    -side 4    -pad_name VSS_R_2              -order 90
set_pad_physical_constraints    -side 4    -pad_name sdi_C_data_7_i       -order 91
set_pad_physical_constraints    -side 4    -pad_name VDD_R_1              -order 92
set_pad_physical_constraints    -side 4    -pad_name sdi_C_tkn_ex_o       -order 93
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_1              -order 94
set_pad_physical_constraints    -side 4    -pad_name sdi_C_sclk_ex_i      -order 95
set_pad_physical_constraints    -side 4    -pad_name V33_R_1              -order 96
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_5        -order 97
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_4        -order 98
set_pad_physical_constraints    -side 4    -pad_name VSS_R_1              -order 99
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_3        -order 100
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_2        -order 101
set_pad_physical_constraints    -side 4    -pad_name VDD_R_0              -order 102
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_1        -order 103
set_pad_physical_constraints    -side 4    -pad_name FILLER_20_R_0        -order 104
set_pad_physical_constraints    -side 4    -pad_name VZZ_R_0              -order 105
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_5_R_1      -order 106
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_10_R_1     -order 107
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_20_R_1     -order 108
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_10_R_1     -order 109
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20A_R_1    -order 110
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20B_R_1    -order 111
set_pad_physical_constraints    -side 4    -pad_name V33_R_0              -order 112
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_5_R_0      -order 113
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_10_R_0     -order 114
set_pad_physical_constraints    -side 4    -pad_name FILLER_35_20_R_0     -order 115
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_10_R_0     -order 116
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20A_R_0    -order 117
set_pad_physical_constraints    -side 4    -pad_name FILLER_50_20B_R_0    -order 118
set_pad_physical_constraints    -side 4    -pad_name VSS_R_0              -order 119
