###############################################################
#  Generated by:      Cadence Innovus 15.21-s080_1
#  OS:                Linux x86_64(Host ID vlsipool-j01.eecs.umich.edu)
#  Generated on:      Thu Apr 20 17:52:50 2017
###############################################################


# bump_connect_target
addBumpConnectTargetConstraint -bump bumpF6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU21 -PGConnectType stripe

addBumpConnectTargetConstraint -instName VDD_B_1 -bump bumpY26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_2 -bump bumpU24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_3 -bump bumpS26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_4 -bump bumpP22 -pinName VDD -portNum 3
# addBumpConnectTargetConstraint -instName VDD_B_5 -bump bumpN24 -pinName VDD -portNum 3
# addBumpConnectTargetConstraint -instName VDD_B_6 -bump bumpM24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_9 -bump bumpF24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_10 -bump bumpB26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_1 -bump bumpA25 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_2 -bump bumpC21 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_3 -bump bumpA19 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_4 -bump bumpE16 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_5 -bump bumpC14 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_6 -bump bumpC13 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_7 -bump bumpE11 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_8 -bump bumpA8 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_9 -bump bumpC6 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_10 -bump bumpA2 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_1 -bump bumpZ25 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_2 -bump bumpX21 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_3 -bump bumpZ19 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_4 -bump bumpV16 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_5 -bump bumpX14 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_6 -bump bumpX13 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_7 -bump bumpV11 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_8 -bump bumpZ8 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_9 -bump bumpX6 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_10 -bump bumpZ2 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_1 -bump bumpB1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_2 -bump bumpF3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_3 -bump bumpH1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_4 -bump bumpK5 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_5 -bump bumpM3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_6 -bump bumpN3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_7 -bump bumpP5 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_8 -bump bumpS1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_9 -bump bumpU3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_10 -bump bumpY1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_1 -bump bumpX25 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_2 -bump bumpV26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_3 -bump bumpR23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_4 -bump bumpQ26 -pinName VSS -portNum 3
# addBumpConnectTargetConstraint -instName VSS_B_5 -bump bumpN26 -pinName VSS -portNum 3
# addBumpConnectTargetConstraint -instName VSS_B_6 -bump bumpM26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_9 -bump bumpE26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_10 -bump bumpC25 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_1 -bump bumpB24 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_2 -bump bumpA22 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_3 -bump bumpD18 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_4 -bump bumpA17 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_5 -bump bumpA14 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_6 -bump bumpA13 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_7 -bump bumpA10 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_8 -bump bumpD9 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_9 -bump bumpA5 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_10 -bump bumpB3 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_1 -bump bumpY24 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_2 -bump bumpZ22 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_3 -bump bumpW18 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_4 -bump bumpZ17 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_5 -bump bumpZ14 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_6 -bump bumpZ13 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_7 -bump bumpZ10 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_8 -bump bumpW9 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_9 -bump bumpZ5 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_10 -bump bumpY3 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_1 -bump bumpC2 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_2 -bump bumpE1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_3 -bump bumpI4 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_4 -bump bumpJ1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_5 -bump bumpM1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_6 -bump bumpN1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_7 -bump bumpQ1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_8 -bump bumpR4 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_9 -bump bumpV1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_10 -bump bumpX2 -pinName VSS -portNum 3

addBumpConnectTargetConstraint -instName DVDDTIE_B_1 -bump bumpX24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_2 -bump bumpU26 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_3 -bump bumpP24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDDTIE_B_4 -bump bumpO24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDD_B_5 -bump bumpL24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDD_B_6 -bump bumpK24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_7 -bump bumpF26 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_8 -bump bumpC24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_1 -bump bumpB25 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_2 -bump bumpA21 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_3 -bump bumpC16 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_4 -bump bumpC15 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_5 -bump bumpC12 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_6 -bump bumpC11 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_7 -bump bumpA6 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_8 -bump bumpB2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_1 -bump bumpY25 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_2 -bump bumpZ21 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_3 -bump bumpX16 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_4 -bump bumpX15 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_5 -bump bumpX12 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_6 -bump bumpX11 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_7 -bump bumpZ6 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_8 -bump bumpY2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_1 -bump bumpC3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_2 -bump bumpF1 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_3 -bump bumpK3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_4 -bump bumpL3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_5 -bump bumpO3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_6 -bump bumpP3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_7 -bump bumpU1 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_8 -bump bumpX3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_1 -bump bumpV22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_2 -bump bumpT24 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_3 -bump bumpP25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_4 -bump bumpO25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_5 -bump bumpL25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_6 -bump bumpK25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_7 -bump bumpG24 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_8 -bump bumpE22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_1 -bump bumpD23 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_2 -bump bumpC20 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_3 -bump bumpB16 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_4 -bump bumpB15 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_5 -bump bumpB12 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_6 -bump bumpB11 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_7 -bump bumpC7 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_8 -bump bumpD4 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_1 -bump bumpW23 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_2 -bump bumpX20 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_3 -bump bumpY16 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_4 -bump bumpY15 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_5 -bump bumpY12 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_6 -bump bumpY11 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_7 -bump bumpX7 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_8 -bump bumpW4 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_1 -bump bumpE5 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_2 -bump bumpG3 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_3 -bump bumpK2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_4 -bump bumpL2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_5 -bump bumpO2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_6 -bump bumpP2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_7 -bump bumpT3 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_8 -bump bumpV5 -pinName DVSS -portNum 3

# PLL Power Bumps
addBumpConnectTargetConstraint -instName PLL_SECTION_VDD_SIG_1 -bump bumpO22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VSS_SIG_1 -bump bumpO23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VDD_SIG_2 -bump bumpL22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VSS_SIG_2 -bump bumpK26 -pinName VSS -portNum 3


# LDO Power Bumps
addBumpConnectTargetConstraint -instName LDO_SECTION_VDD_B_7 -bump bumpK22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VDD_B_8 -bump bumpH26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VSS_B_7 -bump bumpJ26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VSS_B_8 -bump bumpI23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVSS_SIG_1 -bump bumpJ25 -pinName AVSSC -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVDD_SIG_1 -bump bumpJ24 -pinName AVDDC -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VDDIO -bump bumpI25 -pinName VDDIAC -portNum 2
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVSS_SIG_2 -bump bumpJ22 -pinName AVSSC -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVDD_SIG_2 -bump bumpI24 -pinName AVDDC -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VDDC -bump bumpG25 -pinName VDDIAC -portNum 2
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVSS_SIG_3 -bump bumpH23 -pinName AVSSC -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_PAVDD_SIG_3 -bump bumpH22 -pinName AVDDC -portNum 3


# Re-allocated DVDD/DVSS Bumps
addBumpConnectTargetConstraint -instName DVDD_SIG_B_1 -bump bumpW25 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_B_1 -bump bumpV24 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_B_2 -bump bumpR22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_B_2 -bump bumpS25 -pinName DVDD -portNum 3

addBumpConnectTargetConstraint -instName DVDD_SIG_L_1 -bump bumpB23 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_L_1 -bump bumpC22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_L_2 -bump bumpE18 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_L_2 -bump bumpB19 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_L_3 -bump bumpB8 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_L_3 -bump bumpE9 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_L_4 -bump bumpC5 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_L_4 -bump bumpB4 -pinName DVSS -portNum 3

addBumpConnectTargetConstraint -instName DVDD_SIG_R_1 -bump bumpX5 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_R_1 -bump bumpZ4 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_R_2 -bump bumpY8 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_R_2 -bump bumpV9 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_R_3 -bump bumpY19 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_R_3 -bump bumpV18 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_R_4 -bump bumpX22 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_R_4 -bump bumpY23 -pinName DVSS -portNum 3

addBumpConnectTargetConstraint -instName DVDD_SIG_T_1 -bump bumpD2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_T_1 -bump bumpE3 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_T_2 -bump bumpI5 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_T_2 -bump bumpH2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_T_3 -bump bumpR5 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_T_3 -bump bumpS2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVDD_SIG_T_4 -bump bumpW1 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_SIG_T_4 -bump bumpV3 -pinName DVSS -portNum 3




# bump_connect_target end
