set_pad_physical_constraints -side 1 -pad_name corner_ul
set_pad_physical_constraints -side 2 -pad_name corner_ur
set_pad_physical_constraints -side 3 -pad_name corner_lr
set_pad_physical_constraints -side 4 -pad_name corner_ll

set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_6
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_6
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_16
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_15
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_15
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_14
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_sclk_ex_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_5
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_tkn_ex_o
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_5
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_7_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_14
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_6_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_13
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_5_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_13
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_4_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_12
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_7_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_12
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_sclk_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_11
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_6_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_4
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_token_o
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_4
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_5_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_11
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_ncmd_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_10
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_3_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_10
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_2_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_9
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_1_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_9
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_B_data_0_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_8
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_4_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_8
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name clk_0_n_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_7
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name clk_0_p_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_3
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_3_o
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_3
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_0_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_7
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_1_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_6
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_2_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_6
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_ncmd_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_5
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_2_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_5
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_sclk_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_4
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_1_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_2
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_token_o
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_2
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_L_0_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_4
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_3_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_3
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_4_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_3
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_5_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_2
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_6_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_2
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_data_7_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_1
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_tkn_ex_o
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_1
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_A_sclk_ex_i
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_1
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_1
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_L_0
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_L_0
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_L_0
set_pad_physical_constraints -side 2 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_L_0

set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_0
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_0
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_0
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_0
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_1
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_1
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_tkn_ex_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_1
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_sclk_ex_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_1
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_8_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_2
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_7_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_2
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_6_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_2
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_5_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_2
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_4_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_3
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_3_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_3
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_2_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_3
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_1_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_3
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_data_0_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_4
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_ncmd_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_4
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_token_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_4
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_T_0_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_4
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_A_sclk_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_5
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_T_1_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_5
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name SMA_out_p_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_5
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name SMA_out_n_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_5
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name reset_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_6
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_T_2_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_6
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name SMA_in_p_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_7
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name SMA_in_n_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_7
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_sclk_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_6
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name JTAG_TDO_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_6
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_token_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_8
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_ncmd_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_8
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_0_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_7
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_1_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_7
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_2_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_9
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_3_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_9
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_4_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_8
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_5_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_8
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_6_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_10
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_data_7_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_10
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_sclk_ex_o
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_9
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_B_tkn_ex_i
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_9
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_11
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_T_11
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_T_10
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_T_10
set_pad_physical_constraints -side 3 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_T_12

set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_6
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_6
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_16
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_15
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_15
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_14
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_sclk_ex_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_5
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_tkn_ex_o
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_5
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_7_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_14
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_6_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_13
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_5_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_13
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_4_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_12
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_7_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_12
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_sclk_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_11
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_6_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_4
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_token_o
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_4
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_5_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_11
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_ncmd_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_10
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_3_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_10
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_2_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_9
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_1_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_9
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_D_data_0_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_8
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_4_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_8
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name clk_1_n_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_7
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name clk_1_p_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_3
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_3_o
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_3
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_0_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_7
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_1_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_6
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_2_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_6
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_ncmd_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_5
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_2_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_5
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_sclk_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_4
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_1_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_2
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_token_o
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_2
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name misc_R_0_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_4
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_3_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_3
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_4_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_3
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_5_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_2
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_6_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_2
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_data_7_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_1
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_tkn_ex_o
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_1
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdi_C_sclk_ex_i
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_1
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_1
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_R_0
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_R_0
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_R_0
set_pad_physical_constraints -side 4 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_R_0

set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_0
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_0
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_0
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_0
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_1
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_1
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_tkn_ex_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_1
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_sclk_ex_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_1
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_8_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_2
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_7_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_2
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_6_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_2
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_5_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_2
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_4_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_3
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_3_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_3
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_2_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_3
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_1_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_3
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_data_0_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_4
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_ncmd_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_4
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_token_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_4
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name JTAG_TMS_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_4
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_C_sclk_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_5
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name JTAG_TDI_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_5
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name BREAKER_B_0
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name PLL_VDD_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_5
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name PLL_VSS_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_5
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name PLL_CLK_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_6
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name PLL_V33_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_6
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name PLL_VZZ_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name BREAKER_B_1
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_7
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name JTAG_TCK_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_7
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_sclk_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_6
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name JTAG_TRST_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_6
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_token_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_8
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_ncmd_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_8
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_0_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_7
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_1_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_7
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_2_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_9
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_3_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_9
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_4_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_8
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_5_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_8
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_6_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_10
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_data_7_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_10
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_sclk_ex_o
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_9
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name sdo_D_tkn_ex_i
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_9
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_11
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VSS_B_11
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name V33_B_10
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VZZ_B_10
set_pad_physical_constraints -side 1 -min_left_iospace 14 -min_right_iospace 14 -pad_name VDD_B_12
