#!/usr/bin/python
#
# MBT 12/10/14
#
#

import sys;
import re;

# we flip all inputs and output
#

print "// DO NOT MODIFY; AUTOGENERATED BY invert_pinout.py";
for line in sys.stdin :
    newline = re.sub("input","z3z3z3z3",line)
    newline = re.sub("output","input",newline)
    newline = re.sub("z3z3z3z3","output",newline)
    newline = re.sub("XTC_OUT","XTC_TMP",newline)
    newline = re.sub("XTC_IN","XTC_OUT",newline)
    newline = re.sub("XTC_TMP","XTC_IN",newline)
    newline = re.sub("p_(\w*)_i",r"p_\1_X",newline)
    newline = re.sub("p_(\w*)_o",r"p_\1_i",newline)
    newline = re.sub("p_(\w*)_X",r"p_\1_o",newline)
    print newline,
    
