###############################################################
#  Generated by:      Cadence Innovus 15.21-s080_1
#  OS:                Linux x86_64(Host ID vlsipool-j01.eecs.umich.edu)
#  Generated on:      Thu Apr 20 17:52:50 2017
###############################################################


# bump_connect_target
addBumpConnectTargetConstraint -bump bumpF6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpF21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpG21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpH21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpI21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpJ21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpK21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpL21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpM21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpN21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpO21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpP21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpQ21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpR21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpS21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpT21 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU6 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU7 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU8 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU9 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU10 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU11 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU12 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU13 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU14 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU15 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU16 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU17 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU18 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU19 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU20 -PGConnectType stripe
addBumpConnectTargetConstraint -bump bumpU21 -PGConnectType stripe

addBumpConnectTargetConstraint -instName VDD_B_1 -bump bumpY26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_2 -bump bumpU24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_3 -bump bumpS26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_4 -bump bumpP22 -pinName VDD -portNum 3
# addBumpConnectTargetConstraint -instName VDD_B_5 -bump bumpN24 -pinName VDD -portNum 3
# addBumpConnectTargetConstraint -instName VDD_B_6 -bump bumpM24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VDD_B_7 -bump bumpK22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VDD_B_8 -bump bumpH26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_9 -bump bumpF24 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_B_10 -bump bumpB26 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_1 -bump bumpA25 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_2 -bump bumpC21 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_3 -bump bumpA19 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_4 -bump bumpE16 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_5 -bump bumpC14 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_6 -bump bumpC13 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_7 -bump bumpE11 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_8 -bump bumpA8 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_9 -bump bumpC6 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_L_10 -bump bumpA2 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_1 -bump bumpZ25 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_2 -bump bumpX21 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_3 -bump bumpZ19 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_4 -bump bumpV16 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_5 -bump bumpX14 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_6 -bump bumpX13 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_7 -bump bumpV11 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_8 -bump bumpZ8 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_9 -bump bumpX6 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_R_10 -bump bumpZ2 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_1 -bump bumpB1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_2 -bump bumpF3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_3 -bump bumpH1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_4 -bump bumpK5 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_5 -bump bumpM3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_6 -bump bumpN3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_7 -bump bumpP5 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_8 -bump bumpS1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_9 -bump bumpU3 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VDD_T_10 -bump bumpY1 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_1 -bump bumpX25 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_2 -bump bumpV26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_3 -bump bumpR23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_4 -bump bumpQ26 -pinName VSS -portNum 3
# addBumpConnectTargetConstraint -instName VSS_B_5 -bump bumpN26 -pinName VSS -portNum 3
# addBumpConnectTargetConstraint -instName VSS_B_6 -bump bumpM26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VSS_B_7 -bump bumpJ26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName LDO_SECTION_VSS_B_8 -bump bumpI23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_9 -bump bumpE26 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_B_10 -bump bumpC25 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_1 -bump bumpB24 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_2 -bump bumpA22 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_3 -bump bumpD18 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_4 -bump bumpA17 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_5 -bump bumpA14 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_6 -bump bumpA13 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_7 -bump bumpA10 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_8 -bump bumpD9 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_9 -bump bumpA5 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_L_10 -bump bumpB3 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_1 -bump bumpY24 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_2 -bump bumpZ22 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_3 -bump bumpW18 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_4 -bump bumpZ17 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_5 -bump bumpZ14 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_6 -bump bumpZ13 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_7 -bump bumpZ10 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_8 -bump bumpW9 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_9 -bump bumpZ5 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_R_10 -bump bumpY3 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_1 -bump bumpC2 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_2 -bump bumpE1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_3 -bump bumpI4 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_4 -bump bumpJ1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_5 -bump bumpM1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_6 -bump bumpN1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_7 -bump bumpQ1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_8 -bump bumpR4 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_9 -bump bumpV1 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName VSS_T_10 -bump bumpX2 -pinName VSS -portNum 3

addBumpConnectTargetConstraint -instName DVDDTIE_B_1 -bump bumpX24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_2 -bump bumpU26 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_3 -bump bumpP24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDD_B_4 -bump bumpO24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDD_B_5 -bump bumpL24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVDD_B_6 -bump bumpK24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_7 -bump bumpF26 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_B_8 -bump bumpC24 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_1 -bump bumpB25 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_2 -bump bumpA21 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_3 -bump bumpC16 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_4 -bump bumpC15 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_5 -bump bumpC12 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_6 -bump bumpC11 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_7 -bump bumpA6 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_L_8 -bump bumpB2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_1 -bump bumpY25 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_2 -bump bumpZ21 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_3 -bump bumpX16 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_4 -bump bumpX15 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_5 -bump bumpX12 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_6 -bump bumpX11 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_7 -bump bumpZ6 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_R_8 -bump bumpY2 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_1 -bump bumpC3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_2 -bump bumpF1 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_3 -bump bumpK3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_4 -bump bumpL3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_5 -bump bumpO3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_6 -bump bumpP3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_7 -bump bumpU1 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVDD_T_8 -bump bumpX3 -pinName DVDD -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_1 -bump bumpV22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_2 -bump bumpT24 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_3 -bump bumpP25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_4 -bump bumpO25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_5 -bump bumpL25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_DVSS_B_6 -bump bumpK25 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_7 -bump bumpG24 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_B_8 -bump bumpE22 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_1 -bump bumpD23 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_2 -bump bumpC20 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_3 -bump bumpB16 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_4 -bump bumpB15 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_5 -bump bumpB12 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_6 -bump bumpB11 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_7 -bump bumpC7 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_L_8 -bump bumpD4 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_1 -bump bumpW23 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_2 -bump bumpX20 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_3 -bump bumpY16 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_4 -bump bumpY15 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_5 -bump bumpY12 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_6 -bump bumpY11 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_7 -bump bumpX7 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_R_8 -bump bumpW4 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_1 -bump bumpE5 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_2 -bump bumpG3 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_3 -bump bumpK2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_4 -bump bumpL2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_5 -bump bumpO2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_6 -bump bumpP2 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_7 -bump bumpT3 -pinName DVSS -portNum 3
addBumpConnectTargetConstraint -instName DVSS_T_8 -bump bumpV5 -pinName DVSS -portNum 3



addBumpConnectTargetConstraint -instName PLL_SECTION_VDD_1 -bump bumpO22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VSS_1 -bump bumpO23 -pinName VSS -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VDD_2 -bump bumpL22 -pinName VDD -portNum 3
addBumpConnectTargetConstraint -instName PLL_SECTION_VSS_2 -bump bumpK26 -pinName VSS -portNum 3


# addBumpConnectTargetConstraint -instName SIG_B_1 -bump bumpW24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_2 -bump bumpV23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_3 -bump bumpU22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_4 -bump bumpX26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_5 -bump bumpW25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_6 -bump bumpV24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_7 -bump bumpU23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_8 -bump bumpW26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_9 -bump bumpV25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_10 -bump bumpT22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_11 -bump bumpT23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_12 -bump bumpU25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_13 -bump bumpS22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_14 -bump bumpT25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_15 -bump bumpS23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_16 -bump bumpT26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_17 -bump bumpS24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_18 -bump bumpR22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_19 -bump bumpS25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_20 -bump bumpR24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_21 -bump bumpQ22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_22 -bump bumpR25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_23 -bump bumpR26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_24 -bump bumpQ23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_25 -bump bumpQ24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_26 -bump bumpQ25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_27 -bump bumpP23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_32 -bump bumpN22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_33 -bump bumpN23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_34 -bump bumpN25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_35 -bump bumpM25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_36 -bump bumpM23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_37 -bump bumpM22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_39 -bump bumpL23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_42 -bump bumpK23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_43 -bump bumpJ25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_44 -bump bumpJ24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_45 -bump bumpI26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_46 -bump bumpJ23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_47 -bump bumpI25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_48 -bump bumpJ22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_49 -bump bumpI24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_50 -bump bumpH25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_51 -bump bumpI22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_52 -bump bumpG26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_53 -bump bumpH24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_54 -bump bumpG25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_55 -bump bumpH23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_56 -bump bumpH22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_57 -bump bumpF25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_58 -bump bumpG23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_59 -bump bumpE25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_60 -bump bumpG22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_61 -bump bumpD26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_62 -bump bumpF23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_63 -bump bumpE24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_64 -bump bumpD25 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_65 -bump bumpF22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_66 -bump bumpE23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_67 -bump bumpD24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_D_28 -bump bumpP26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_D_31 -bump bumpO26 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_B_D_38 -bump bumpL26 -pinName PAD -portNum 1

# addBumpConnectTargetConstraint -instName SIG_L_1 -bump bumpC23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_2 -bump bumpD22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_3 -bump bumpE21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_4 -bump bumpA24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_5 -bump bumpB23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_6 -bump bumpC22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_7 -bump bumpD21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_8 -bump bumpA23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_9 -bump bumpB22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_10 -bump bumpE20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_11 -bump bumpD20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_12 -bump bumpB21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_13 -bump bumpE19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_14 -bump bumpD19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_15 -bump bumpB20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_16 -bump bumpA20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_17 -bump bumpC19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_18 -bump bumpE18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_19 -bump bumpB19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_20 -bump bumpC18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_21 -bump bumpE17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_22 -bump bumpB18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_23 -bump bumpD17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_24 -bump bumpA18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_25 -bump bumpC17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_26 -bump bumpB17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_27 -bump bumpD16 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_29 -bump bumpE15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_30 -bump bumpD15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_32 -bump bumpE14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_33 -bump bumpD14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_34 -bump bumpB14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_35 -bump bumpB13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_36 -bump bumpD13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_37 -bump bumpE13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_39 -bump bumpD12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_40 -bump bumpE12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_42 -bump bumpD11 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_43 -bump bumpB10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_44 -bump bumpC10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_45 -bump bumpA9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_46 -bump bumpD10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_47 -bump bumpB9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_48 -bump bumpE10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_49 -bump bumpC9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_50 -bump bumpB8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_51 -bump bumpE9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_52 -bump bumpC8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_53 -bump bumpA7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_54 -bump bumpB7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_55 -bump bumpD8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_56 -bump bumpE8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_57 -bump bumpB6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_58 -bump bumpD7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_59 -bump bumpE7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_60 -bump bumpB5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_61 -bump bumpA4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_62 -bump bumpD6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_63 -bump bumpC5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_64 -bump bumpB4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_65 -bump bumpA3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_66 -bump bumpE6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_67 -bump bumpD5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_68 -bump bumpC4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_D_28 -bump bumpA16 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_D_31 -bump bumpA15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_D_38 -bump bumpA12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_L_D_41 -bump bumpA11 -pinName PAD -portNum 1


# addBumpConnectTargetConstraint -instName SIG_R_1 -bump bumpX4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_2 -bump bumpZ3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_3 -bump bumpW5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_4 -bump bumpY4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_5 -bump bumpX5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_6 -bump bumpZ4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_7 -bump bumpV6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_8 -bump bumpY5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_9 -bump bumpW6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_10 -bump bumpV7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_11 -bump bumpY6 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_12 -bump bumpW7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_13 -bump bumpV8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_14 -bump bumpY7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_15 -bump bumpZ7 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_16 -bump bumpW8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_17 -bump bumpX8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_18 -bump bumpY8 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_19 -bump bumpV9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_20 -bump bumpX9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_21 -bump bumpY9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_22 -bump bumpV10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_23 -bump bumpZ9 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_24 -bump bumpW10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_25 -bump bumpX10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_26 -bump bumpY10 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_27 -bump bumpW11 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_29 -bump bumpV12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_30 -bump bumpW12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_32 -bump bumpV13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_33 -bump bumpW13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_34 -bump bumpY13 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_35 -bump bumpY14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_36 -bump bumpW14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_37 -bump bumpV14 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_39 -bump bumpW15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_40 -bump bumpV15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_42 -bump bumpW16 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_43 -bump bumpY17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_44 -bump bumpX17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_45 -bump bumpZ18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_46 -bump bumpW17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_47 -bump bumpY18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_48 -bump bumpV17 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_49 -bump bumpX18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_50 -bump bumpY19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_51 -bump bumpV18 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_52 -bump bumpZ20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_53 -bump bumpX19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_54 -bump bumpY20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_55 -bump bumpW19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_56 -bump bumpV19 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_57 -bump bumpY21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_58 -bump bumpW20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_59 -bump bumpY22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_60 -bump bumpV20 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_61 -bump bumpZ23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_62 -bump bumpW21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_63 -bump bumpX22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_64 -bump bumpY23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_65 -bump bumpZ24 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_66 -bump bumpV21 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_67 -bump bumpW22 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_68 -bump bumpX23 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_D_28 -bump bumpZ11 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_D_31 -bump bumpZ12 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_D_38 -bump bumpZ15 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_R_D_41 -bump bumpZ16 -pinName PAD -portNum 1


# addBumpConnectTargetConstraint -instName SIG_T_1 -bump bumpD3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_2 -bump bumpE4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_3 -bump bumpF5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_4 -bump bumpC1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_5 -bump bumpD2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_6 -bump bumpE3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_7 -bump bumpF4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_8 -bump bumpD1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_9 -bump bumpG5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_10 -bump bumpE2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_11 -bump bumpG4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_12 -bump bumpF2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_13 -bump bumpH5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_14 -bump bumpH4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_15 -bump bumpG2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_16 -bump bumpH3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_17 -bump bumpG1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_18 -bump bumpI5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_19 -bump bumpH2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_20 -bump bumpI3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_21 -bump bumpJ5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_22 -bump bumpI2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_23 -bump bumpJ4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_24 -bump bumpI1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_25 -bump bumpJ3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_26 -bump bumpJ2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_27 -bump bumpK4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_29 -bump bumpL5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_30 -bump bumpL4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_32 -bump bumpM5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_33 -bump bumpM4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_34 -bump bumpM2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_35 -bump bumpN2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_36 -bump bumpN4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_37 -bump bumpN5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_39 -bump bumpO4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_40 -bump bumpO5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_42 -bump bumpP4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_43 -bump bumpQ2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_44 -bump bumpQ3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_45 -bump bumpQ4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_46 -bump bumpR1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_47 -bump bumpQ5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_48 -bump bumpR2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_49 -bump bumpR3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_50 -bump bumpR5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_51 -bump bumpS2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_52 -bump bumpS3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_53 -bump bumpS4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_54 -bump bumpT1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_55 -bump bumpT2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_56 -bump bumpS5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_57 -bump bumpT4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_58 -bump bumpU2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_59 -bump bumpT5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_60 -bump bumpU4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_61 -bump bumpV2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_62 -bump bumpU5 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_63 -bump bumpW1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_64 -bump bumpV3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_65 -bump bumpW2 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_66 -bump bumpV4 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_67 -bump bumpX1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_68 -bump bumpW3 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_D_28 -bump bumpK1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_D_31 -bump bumpL1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_D_38 -bump bumpO1 -pinName PAD -portNum 1
# addBumpConnectTargetConstraint -instName SIG_T_D_41 -bump bumpP1 -pinName PAD -portNum 1


# bump_connect_target end
