// MBT 8-17-2016
// inverted version of bsg_two pinout; for testbenches
// AUTOGENERATED BY invert_pinout.py and then modified
//
// **********************************************************************
// UCSD BSG Two Pinout (Based on UCSD BGA 332)
//
// This file defines all of the pads that are used for a given pinout of
// a package. It would change if we reversed the direction of a pad. It
// is recommended not to change the name of the
// pin (except the _i or _o) at this level so that we can maintain canonical
// naming for the package; instead just do an assign of a wire to rename.
//
// convention:
//
// - the output ports have a prefix of "p_"
// - the corresponding signals have no prefix
//   and have a suffix of _int.
// - the IO pad names are consistent with the
//   BGA 332 pinout names (e.g, sdi_B_data_7_i, sdi_B_ncmd_i)
//

//module
// bsg_two
(
 input p_PWR_RSTN,
 // *******************************************************************
 // all "100-ohm impedance-controlled-in-package" differential pairs
 //

 // unused differential outputs
 // we give these as inputs, and then go high-impedance
   output p_clk_0_p_o   , output p_clk_0_n_o
 , output  p_clk_1_p_o  , output p_clk_1_n_o

 // *******************************************************************
 // ultra-shielded "50-ohm impedance-controlled-in-package" clock for PLL
 , output   p_PLL_CLK_o

 // *******************************************************************
 // all "50-ohm impedance-controlled-in-package" signals starting here
 // these are length matched within 1.55 mm length and
 // .76 mm bond wire length.

 // output clocks for output channels D,C,B,A
 , output  [3:0] p_sdi_sclk_o

 // output valids for output channels D,C,B,A
 , output  [3:0] p_sdi_ncmd_o

 // output datas for output channels D,C,B,A
 , output  [7:0] p_sdi_A_data_o, output [7:0] p_sdi_B_data_o
 , output  [7:0] p_sdi_C_data_o, output [7:0] p_sdi_D_data_o

 // input tokens for output channels D,C,B,A
 , input [3:0] p_sdi_token_i

 // input clocks for input channels D,C,B,A
 , input [3:0] p_sdo_sclk_i

 // input valids for input channels
 , input [3:0] p_sdo_ncmd_i

 // input data for out channels
 , input [7:0] p_sdo_A_data_i, input [7:0] p_sdo_B_data_i
 , input [7:0] p_sdo_C_data_i, input [7:0] p_sdo_D_data_i

 // extra input datas
 , input p_sdo_A_data_8_i , input p_sdo_C_data_8_i

 // output tokens for input channels
 , output  [3:0] p_sdo_token_o

 // spare clocks, length matched to channels
 , output  [3:0] p_sdi_sclk_ex_o
 , input [3:0] p_sdo_sclk_ex_i

 // spare tokens for output and input channels
 , input [3:0] p_sdi_tkn_ex_i
 , output  [3:0] p_sdo_tkn_ex_o

 // *******************************************************************
 // all "50-ohm impedance-controlled-in-package", starting here
 // but are next to clock or token signals
 // and are not length-matched

 , output  p_misc_T_0_o, output p_misc_T_1_o, output p_misc_T_2_o

 , output  p_misc_L_7_o, output  p_misc_R_7_o
 , output  p_misc_L_6_o, output  p_misc_R_6_o
 , output  p_misc_L_5_o, output  p_misc_R_5_o
 , output  p_misc_L_4_o, output  p_misc_R_4_o

 // L3 and R3 are input pads because it works with the pad ring
 , input p_misc_L_3_i, input p_misc_R_3_i

 , output  p_misc_L_2_o, output  p_misc_R_2_o
 , output  p_misc_L_1_o, output  p_misc_R_1_o
 , output  p_misc_L_0_o, output  p_misc_R_0_o

 , output  p_reset_o

 // for JTAG, or other purposes
 , output  p_JTAG_TMS_o
 , output  p_JTAG_TDI_o
 , output  p_JTAG_TCK_o
 , output  p_JTAG_TRST_o
 , input p_JTAG_TDO_i
 );

// End UCSD BGA 332 PAD Definitions
// **********************************************************************


