genvar i;

`ifndef BSG_PAD_INPUT_PULLDOWN
BSG_PAD_INPUT_PULLDOWN should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_A
BSG_PAD_OUTPUT_A should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_B
BSG_PAD_OUTPUT_B should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_C
BSG_PAD_OUTPUT_C should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_D
BSG_PAD_OUTPUT_D should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_SLOW
BSG_PAD_OUTPUT_SLOW should be defined!
`endif

`ifndef BSG_PAD_DISABLE
BSG_PAD_DISABLE should be defined!
`endif

`ifndef BSG_PAD_INOUT
BSG_PAD_INOUT should be defined!
`endif

`BSG_IO_IN  (pad_LINK_0,   `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_LINK_1,   `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_LINK_2,   `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_LINK_3,   `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_LINK_v,   `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_LINK_clk, `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_OUT (pad_LINK_tkn, `BSG_PAD_OUTPUT_SLOW)

`BSG_IO_OUT (pad_LINK_0,   `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_OUT (pad_LINK_1,   `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_OUT (pad_LINK_2,   `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_OUT (pad_LINK_3,   `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_OUT (pad_LINK_v,   `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_OUT (pad_LINK_clk, `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_IN  (pad_LINK_tkn, `BSG_PAD_INPUT_PULLDOWN)

`BSG_IO_IN  (pad_TAG_clk,  `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_IN  (pad_TAG_data, `BSG_PAD_INPUT_PULLDOWN)

`BSG_IO_IN  (pad_EXT_clk, `BSG_PAD_INPUT_PULLDOWN)
`BSG_IO_OUT (pad_MON_clk, `BSG_PAD_OUTPUT_SLOW)
`BSG_IO_IN  (pad_DISABLE, `BSG_PAD_INPUT_PULLDOWN)
